application:
  name: @project.artifactId@
  name-formated: @project.name@
  version: @project.version@
server:
  servlet:
    contextPath: /validationexample
spring:
  data:
    rest:
      basePath: /api/rest
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
