application:
  name: @project.artifactId@
  name-formated: @project.name@
  version: @project.version@
server:
  contextPath: /validationexample
spring:
  data:
    rest:
      basePath: /api/rest
entitymanager:
  packagesToScan: de.knightsoftnet.validationexample.shared.models